### ISSUE TITLE
SM Crash after latest Update

### ISSUE THREAD

**Issue by ASopH** [regorxxx/Not-A-Waveform-Seekbar-SMP#2]
Hi,
after latest Update will crash:

Error: Spider Monkey Panel v1.6.1 ({E9A6547D-D41E-4215-9A2E-148DAB668A6D})
include failed:
include failed:
missing { before function body

File: helpers_xxx_basic_js.js
Line: 68, Column: 40
Stack trace:
  @helpers_xxx.js:21:1
  @seekbar.js:3:1

btw. Playlist manager crashes too

**Comment by ASopH** [comment]
Hi,
you're quick :-) 
thank you - nice job
greetings

**Comment by regorxxx** [comment]
Yep, messed all the repositories with a bad file. But fixed it immediately.
