### ISSUE TITLE
"Analyzing track" text not visible with White background

### ISSUE THREAD

**Issue by smoralis** [regorxxx/Not-A-Waveform-Seekbar-SMP#3]
seekbar_xxx.js
fixed by modifying line 523

`gr.GdiDrawText('Analyzing track...', this.ui.gFont, this.ui.colors.bg == 0xFFFFFFFF ? 0xFF000000:0xFFFFFFFF, this.x + this.marginW, 0, this.w - this.marginW * 2, this.h, center);`

**Comment by regorxxx** [comment]
Ups! Thanks :)
